name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: lukka/get-cmake@v3.26.3
      with:
        cmakeVersion: '3.26.3'  # Исправлено с 'cmake-version' на 'cmakeVersion'

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential dpkg-dev

    - name: Set build number
      id: set_build_number
      run: |
        echo "GITHUB_RUN_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV
        echo "Build number set to $GITHUB_RUN_NUMBER"

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Make binary executable
      run: chmod +x build/helloworld

    - name: Run program
      run: |
        cd build
        ./helloworld

    - name: Test output
      run: |
        output=$(cd build && ./helloworld)
        echo "$output"
        build_number=$(echo "$output" | head -n 1 | awk '{print $2}')
        if ! [[ "$build_number" =~ ^[0-9]+$ ]]; then
          echo "Build number is not a valid number."
          exit 1
        fi

    - name: Package binary with CPack
      run: |
        cd build
        cpack -G DEB

    - name: List build directory
      run: |
        echo "Contents of build directory:"
        ls -la build

    - name: Display package contents
      run: |
        PACKAGE_FILE=$(ls build/*.deb | head -n 1)
        echo "Found package: $PACKAGE_FILE"
        if [ ! -f "$PACKAGE_FILE" ]; then
          echo "Debian package not found!"
          exit 1
        fi

    - name: Create release
      id: create_release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.set_build_number.outputs.GITHUB_RUN_NUMBER }}/helloworld-0.0.${{ github.run_number }}-Linux.deb
        asset_name: helloworld-0.0.${{ github.run_number }}-Linux.deb
        asset_content_type: application/octet-stream
