name: Build and Release .deb Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up C++ compiler
      run: sudo apt-get install -y build-essential

    - name: Build binary
      run: |
        g++ -o helloworld_cli main.cpp
        mkdir -p package/usr/local/bin
        cp helloworld_cli package/usr/local/bin/

    - name: Create control file
      run: |
        mkdir -p package/DEBIAN
        echo "Package: helloworld" > package/DEBIAN/control
        echo "Version: 0.0.${{ github.run_number }}" >> package/DEBIAN/control
        echo "Section: utils" >> package/DEBIAN/control
        echo "Priority: optional" >> package/DEBIAN/control
        echo "Architecture: amd64" >> package/DEBIAN/control
        echo "Maintainer: Your Name <your_email@example.com>" >> package/DEBIAN/control
        echo "Description: Hello World CLI tool" >> package/DEBIAN/control
        echo " A simple CLI tool that prints build version and a message." >> package/DEBIAN/control

    - name: Build .deb package
      run: dpkg-deb --build package

    - name: Upload Release Asset
      uses: actions/upload-artifact@v3
      with:
        name: helloworld-0.0.${{ github.run_number }}-Linux.deb
        path: package.deb

    - name: Publish GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: package.deb
